INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('EAGLETONE', 'HOBO', 'À la plage, dans un parc, chez soi, en répétition, en studio ou sur scène, la guitare de voyage Eagletone Hobo s adapte à toutes les situations et tous les environnements.', 92, 103.04, '409-53-2172', 'Naturelle', 1);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('BIRD', 'INSTRUMENTS DG1', 'La gamme Bird acoustique et électro-acoustique a été spécialement pensée pour les guitaristes débutants.', 85, 95.2, '738-14-0742', 'Noir', 1);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('EAGLETONE', 'HOBO', 'Dans un parc, à la plage, chez vous, en répétition, en studio, sur scène... La guitare de voyage Eagletone HOBO s adapte à toutes les situations et tous les environnements, et vous accompagne où que vous alliez !', 164, 183.68, '354-90-4365', 'Noir', 1);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('EAGLETONE', 'CARAVANA D GRANDE BOUCHE', 'A la fois rugueuse et percutante, cette gypsie est idéale pour aller voir du coté swing de la guitare, pure et sans fioriture.', 309, 346.08, '681-14-2990', 'Naturelle', 1);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('BIRD', 'INSTRUMENTS DG1L NATURELLE - GAUCHER', 'La gamme Bird acoustique et électro-acoustique a été spécialement pensée pour les guitaristes débutants.', 99, 110.88, '460-44-0895', 'Naturelle', 1);

INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('BIRD', 'INSTRUMENTS BA620 - COMBO', 'Basses fréquences obligent, les bassistes ont toujours eu besoin d amplis plus puissants que les guitaristes.', 63, 70.56, '538-80-8505', 'Noir', 2);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('EAGLETONE', 'RAGING 20B', 'La gamme des amplis Eagletone s enrichit d un combo basse 20W plein de ressources.', 130, 145.6, '655-26-0915', 'Noir', 2);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('EAGLETONE', 'RAGING 50B', 'Le Raging 50B est un concentré de puissance et de polyvalence.', 245, 274.4, '282-14-1241', 'Noir', 2);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('PHIL JONES', 'DOUBLE 4 70W MICRO COMBO 2X4" NEO', 'Le DOUBLE FOUR est le summum des micro amplis basse.', 618, 692.16, '883-96-4048', 'Noir', 2);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('FENDER', 'RUMBLE 100 (V3), 230V EUR', 'Pour les bassistes de tous niveaux, les combos de basse Rumble ont été repensés et sont à présent incroyablement compacts, portatifs et légers.', 251, 281.12, '218-20-9015', 'Noir', 2);

INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('ROLAND', 'TD-1DMK DOUBLE MESH KIT', 'Si vous rêvez de jouer de la batterie, vous savez à quel point cette envie est tenace.', 548, 613.76, '233-45-0447', 'Noir', 3);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('ALESIS', 'DEBUTKIT - MESH KIT 4 FUTS / 3 CYMBALES', 'La Debut Kit est livré avec absolument tout ce dont vous avez besoin pour commencer à jouer de la batterie.', 383, 428.96, '427-80-5717', 'Noir', 3);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('PEARL DRUMS', 'KIT E/MERGE TRADITIONNAL PACK', 'La toute nouvelle bibliothèque acoustique du MDL-1 a été enregistrée dans l un des studios d enregistrement les plus réputés au monde dans la ville historique Music City USA, Nashville, Tennessee.', 923, 1033.76, '639-16-0672', 'Noir', 3);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('ALESIS', 'PACK CRIMSON II MESH KIT - (5 FUTS 4 CYMBALES) - SPECIAL EDITION + HARDWARE', 'Changement de look et des caractéristiques digne d’une pro !', 400, 448, '734-77-2860', 'Bleu', 3);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('ROLAND', 'TD-07KV', 'Roland présente la V-Drums TD-07KV, un nouveau kit compact à petit prix dans la fameuse famille V-Drums.', 913, 1022.56, '776-45-8744', 'Orange', 3);

INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('STAGG', 'ACB-320', 'Housse standard pour accordéon', 74, 82.88, '186-01-7626', 'Bleu', 4);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('VENTURA', 'BAGS AK-09D20', 'Housse de transport pour accordéon diatonique 2915 et Erica.', 800, 896, '347-91-1815', 'Noir', 4);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('ROLAND', 'FR-1XB BK', 'Les V-Accordéons ont révolutionné le monde de la musique et Roland s’est engagé à fond dans le développement de ces incroyables instruments.', 5980, 6697.6, '781-04-7577', 'Marron', 4);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('HOHNER', '2915 GC EN SOL/DO', 'Le modèle 2915 Gold Brand est l accordéon le plus sonore de toute la gamme Hohner.', 1033, 1156.96, '186-16-1249', 'Naturelle', 4);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('HOHNER', 'GALAAD G/C', 'Les accordéons diatoniques Morgane, Merlin et Galaad sont considérés les mieux à mêmes d interpréter les musiques populaires française, celtique et bretonne. Leu sonorité est exceptionnelle et leur maniement facile.', 294, 329.28, '105-69-8492', 'Orange', 4);

INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('DUALO', 'DU-TOUCH S BK', 'Le Dualo Du-Touch S est un instrument de musique mobile et autonome, doté d un clavier et de tous les outils essentiels pour composer où bon vous semble.', 534, 598.08, '193-77-5015', 'Noir', 5);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('ELEKTRON', 'DIGITONE KEYS', 'Ce synthétiseur numérique polyphonique à 8 voix est une machine performante capable de créer des paysages sonores dignes de vos rêves les plus lointains.', 1008, 1128.96, '885-25-4598', 'Naturelle', 5);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('KORG', 'WAVESTATE', 'La légendaire Wavestation de KORG a introduit le Wave Sequencing dans le monde, transformant des échantillons bruts en sons que personne n avait jamais entendu auparavant.', 478, 535.36, '600-49-7970', 'Noir', 5);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('ELEKTRON', 'DIGITONE', 'L Elektron Digitone montre la façon dont la synthèse FM peut être revitalisée et modernisée.', 491, 549.92, '447-59-5326', 'Bleu', 5);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('ARTURIA', 'MICROFREAK', 'Le synthétiseur numérique pas comme les autres ! Il mélange des oscillateurs à table d onde et des oscillateurs numériques avec des filtres analogiques.', 1687, 1889.44, '757-90-2879', 'Vert', 5);

INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('SENNHEISER', 'HD-280 PRO', 'Le HD 280 Pro est un casque de monitoring de type fermé, destiné aux professionnels.', 780, 873.6, '118-33-5529', 'Noir', 6);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('SENNHEISER', 'HD 200 PRO', 'Ce tout nouveau casque Sennheiser HD200 PRO a été spécifiquement conçu par Sennheiser pour le Home Studio.', 439, 491.68, '827-89-0277', 'Noir', 6);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('BIRD INSTRUMENTS', 'INSTRUMENTS HP-1000', 'Le casque Bird HP-1000 offre une large réponse en fréquences pour une utilisation studio optimale ou pour le jeu d un instrument au casque, tout en restant polyvalent par sa faible impédance qui permet de le connecter à un lecteur mp3, un smartphone ou une tablette.', 68, 76.16, '427-33-5724', 'Noir', 6);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('EAGLETONE', 'ORIGINAL FIRST', 'Que vous soyez ingénieur du son professionnel ou simplement amateur de bonne musique, les casques de monitoring de studio Eagletone vont vous transporter vers de nouvelles dimensions sonores.', 209, 234.08, '371-83-5767', 'Rouge', 6);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('SENNHEISER', 'HD 25', 'Il est une référence incontournable de la gamme casque Sennheiser depuis de nombreuses années. Il s’agit du casque audio professionnel de la série HD 25.', 232, 259.84, '648-66-3338', 'Noir', 6);

INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('DENON', 'PRO DN-280', 'Le Denon Professional DN-280 est un amplificateur compact et puissant conçu pour sommer les signaux stéréo en mono, ce qui en fait une solution idéale pour de nombreuses applications, telles que les services de messagerie, les systèmes de sonorisation et la diffusion de musique d ambiance.', 634, 710.08, '463-82-9658', 'Noir', 7);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('CROWN AUDIO', 'AUDIO XLS 1502', 'XLS DriveCore 2, la nouvelle génération d amplificateurs XLS intègre dans un rack au design élégant un écran LCD plus grand et des fonctionnalités DSP étendues.', 896, 1003.52, '202-26-2633', 'Noir', 7);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('CROWN AUDIO', 'AUDIO CT 875', 'En combinant le nom avec lequel tout a commencé, ComTech, ainsi que la nouvelle génération technologique DriveCore, Crown redéfinit les critères de l installation fixe avec ses nouveaux amplificateurs ComTech DriveCore.', 1954, 2188.48, '232-61-7726', 'Noir', 7);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('CROWN AUDIO', 'AUDIO CDI1000 - AMPLIFICATEUR 2 X 500W / 4 OHMS - 70V + DSP', 'Les amplificateurs CDI (Contractor Digital Intelligence) sont conçus pour l installation fixe.', 1514, 1695.68, '157-76-2182', 'Noir', 7);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('CROWN AUDIO', 'AUDIO XLI2500', 'Les amplificateurs de la série XLi permettent d accéder a la célébre qualité d amplification Crown pour un budget extrémement raisonnable. Disponible sous quatre modéles identiques, a l exception de leur puissance et de leur poids, la série XLi est idéale pour l amplification de systémes de sonorisation fixes ou mobiles.', 455, 509.6, '301-27-0930', 'Noir', 7);

INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('NUMARK', 'MP103USB', 'Lecteur CD MP3 / USB professionnel', 78, 87.36, '742-57-2116', 'Noir', 8);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('PIONEER DJ', 'CDJ-900NXS', 'Ce dernier né prend exemple sur le succès de son prédécesseur, le CDJ-900, et va encore plus loin avec tout un assortiment de nouveautés technologiques comme un écran couleur LCD, les fonctions Beat Divide, Beat Sync sur quatre pistes et la possibilité de lire des morceaux depuis un smartphone.', 1389, 1555.68, '702-22-8125', 'Noir', 8);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('DENON DJ', 'SC6000 PRIME', 'Le SC6000 Prime est également le premier lecteur DJ au monde à intégrer de manière autonome, entre autres métadonnées, l analyse des marqueurs de rythme (beatgrid) et de la clé harmonique des morceaux, offrant dès lors aux DJ un niveau de lisibilité et de réactivité sans précédent.', 1331, 1490.72, '715-12-6171', 'Noir', 8);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('NUMARK', 'NDX500', 'La NDX500 combine lecteur multimédia CD/USB et contrôleur MIDI, et vous permet un accès complet à toute votre bibliothèque musicale, où que vous soyez.', 296, 331.52, '875-96-1793', 'Noir', 8);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('GEMINI', 'CDM-400 BT - CONTRÔLEUR DJ ATUONOME 2 VOIES BLUETOOTH', 'Ce contrôleur DJ est autonome (pas besoin d ordinateur pour l utiliser) et lit les fichiers audio via usb, CD ou encore via Bluetooth de tout appareil (smartphone, ordinateur) avec metteur sans fil.', 364, 407.68, '182-76-1339', 'Noir', 8);

INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('SELMER', 'TENOR AXOS', 'Conçu et fabriqué dans les ateliers Selmer à Mantes-la-Ville, le soin porté à la fabrication du ténor Axos par leurs artisans montre le même niveau d exigence et de savoir-faire que ses aînés.', 2241, 2509.92, '661-14-1459', 'Noir', 9);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('EAGLETONE', 'ROAD AS100', 'La gamme Eagletone ROAD propose un large choix d’instruments à vent, bois et cuivres, destinés aux musiciens apprentis, aux élèves de conservatoire ou d’école de musique et à tous les passionnés de musique au budget serré.', 254, 284.48, '598-77-9000', 'Noir', 9);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('EAGLETONE', 'TENOR HIGHWAY', 'Le saxophone Eagletone Highway a été pensé, conçu et fabriqué pour les musiciens à la recherche d un instrument leur permettant de développer leur propre personnalité grâce à un timbre riche.', 1571, 1759.52, '688-64-6709', 'Noir', 9);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('EAGLETONE', 'DARK HIGHWAY', 'Le saxophone Eagletone Highway a été pensé, conçu et fabriqué pour les musiciens à la recherche d un instrument leur permettant de développer leur propre personnalité grâce à un timbre riche.', 521, 583.52, '868-54-5611', 'Noir', 9);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('SELMER', '180 BEC SAXOPHONE ALTO', 'Selmer Paris propose une large gamme de becs correspondant des esthtiques de son diffrentes, plus ou moins timbres.', 34, 38.08, '463-26-3275', 'Noir', 9);

INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('EAGLETONE', 'RIMINI 4/4', 'Conçue et préparée par un luthier, la gamme de violons Eagletone Rimini se démarque par une qualité de fabrication irréprochable et inégalable dans cette gamme de prix.', 412, 461.44, '245-47-6182', 'Naturelle', 10);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('ANTOINE SONNET', 'VL10 4/4', 'Antoine Sonnet propose une gamme d instruments spécialement adaptée aux musiciens débutants et aux petits budgets.', 505, 565.6, '157-23-2595', 'Naturelle', 10);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('EAGLETONE', 'RIMINI 1/2', 'Conçue et préparée par un luthier, la gamme de violons Eagletone Rimini se démarque par une qualité de fabrication irréprochable et inégalable dans cette gamme de prix.', 975, 1092, '557-82-5440', 'Naturelle', 10);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('ANTOINE SONNET', 'EV10 BK', 'Antoine Sonnet propose une gamme d instruments spécialement adaptée aux musiciens débutants et aux petits budgets.', 358, 400.96, '854-04-5695', 'Noir', 10);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('EAGLETONE', 'PICCINI 4/4', 'Ce violon est entièrement fabriqué à la main dans un bois d érable naturel sec depuis 5 ans.', 692, 775.04, '605-83-4724', 'Naturelle', 10);

INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('ROHEMA', 'BAGUETTE DIRECTION CARBONE MOZART - ÉQUILIBRÉE', 'Rohema Percussion est une entreprise familiale spécialisée dans la fabrication de baguettes et percussions depuis 1888.', 535, 599.2, '740-54-3705', 'Naturelle', 11);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('ROHEMA', 'BAGUETTE DIRECTION CARBONE MAESTRO - ÉQUILIBRÉE', 'Rohema Percussion est une entreprise familiale spécialisée dans la fabrication de baguettes et percussions depuis 1888.', 224, 250.88, '438-60-6547', 'Naturelle', 11);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('ROHEMA', 'BAGUETTE DIRECTION FIBRE DE VERRE MOZART II - ÉQUILIBRÉE', 'Rohema Percussion est une entreprise familiale spécialisée dans la fabrication de baguettes et percussions depuis 1888.', 497, 556.64, '740-50-7732', 'Naturelle', 11);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('ROHEMA', 'BAGUETTE DIRECTION CARBONE BRUCH - ÉQUILIBRÉE', 'Rohema Percussion est une entreprise familiale spécialisée dans la fabrication de baguettes et percussions depuis 1888.', 545, 610.4, '236-69-3689', 'Naturelle', 11);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('ROHEMA', 'BAGUETTE DIRECTION FIBRE DE VERRE SMETANA - ÉQUILIBRÉE', 'Rohema Percussion est une entreprise familiale spécialisée dans la fabrication de baguettes et percussions depuis 1888.', 146, 163.52, '854-06-1738', 'Naturelle', 11);

INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('WOODBRASS', 'GS30 STAND DE GUITARE', 'Stand universel pour guitare et basse', 21, 23.52, '137-60-0487', 'Noir', 12);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('WOODBRASS', 'EGC100 BL ETUI POUR GUITARE ELECTRIQUE', 'Etui pour guitare électrique type Stratocaster, Telecaster mais ne convient pas aux Epiphone type SG...', 75, 84, '154-21-5157', 'Noir', 12);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('WOODBRASS', 'MU30 PUPITRE', 'En acier', 3, 3.36, '785-31-9441', 'Noir', 12);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('EAGLETONE', 'CT50 - ACCORDEUR', 'Une détection rapide et précise.', 39, 43.68, '841-40-5387', 'Noir', 12);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('WOODBRASS', 'ML4 LAMPE DE PUPITRE', 'Cette lampe pour pupitre vous accompagnera partout!', 11, 12.32, '269-56-9574', 'Noir', 12);

INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('EAGLETONE', 'MPW37 + HOUSSE', 'Petit clavier de 4 octaves idéal pour les enfants afin qu ils se familiarisent avec le jeu du clavier, ses petites touches sont adaptées aux plus jeunes musiciens qui pourront également s en servir comme guide-chant.', 30, 33.6, '161-97-0754', 'Naturelle', 13);

INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('EAGLETONE', 'LIL LASER FIREFLY', 'Dynamisez vos soirées avec les Lil Laser d Eagletone. Le Lil Laser Firefly projette un ciel étoilé rouge et vert sur vos murs et plafonds.', 33, 36.96, '459-88-1174', 'Noir', 14);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('EAGLETONE', 'LIL LASER 20', 'Dynamisez vos soirées avec les Lil Laser d Eagletone. Le Lil Laser 20 projette 20 motifs différents sur vos murs et plafonds.', 16, 17.92, '868-48-3089', 'Blanc', 14);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('POWER LIGHTING', 'SATURNE 1K RGB', 'Le SATURNE 1K RGB de POWER LIGHTING est un laser 3 couleurs Rouge, Vert, Bleu d’une puissance de 1000 mW.', 23, 25.76, '244-69-2043', 'Noir', 14);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('CAMEO', 'WOOKIE 200 RGY - LASER ANIMATION RGY 200 MW', 'Le WOOKIE 200 RGY possède une puissance de 200 mW ; il est équipé de lasers à diode et DPSS pour émettre des rayons rouge, vert et jaune d un diamètre de 3 mm et d une divergence extrêmement faible (1 mrad seulement).', 48, 53.76, '647-68-2407', 'Noir', 14);
INSERT INTO Products(pro_marque, pro_name, pro_desc, pro_vente_htva, pro_vente_tvac, pro_ean, pro_color, sub_id) VALUES ('CAMEO', 'ILDA 5 M - CÂBLE RALLONGE ILDA LONGUEUR 5 M AVEC VIS DE SERRAGE', 'Type de produit Matériel pour lasers', 31, 34.72, '823-14-0758', 'Noir', 14);